# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Scheme:
        type: choice
        # Default value if no value is selected
        default: 'AssetStorage'
        # Input has to be provided for the workflow to run
        required: true
        options:
        - AssetStorage
        - AssetStorageBeta
        - AssetStorageRelease
      Note:
        description: 'Add release notes for this build'
        default: 'This build is ready for testing'
        required: true
env:
  dev_build: ${{ vars.DEV_BUILD_NUMBER }}
                

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
        - name: Download dev build number artifact
          uses: actions/download-artifact@v3
          with:
            name: dev_build
            
        - name: Increment Build Number
          id: incr
          run: |
            value = `cat dev_build.txt.txt`
            expr ($value \+ 1) > dev_build.txt
         
        - name: Upload build number
          uses: actions/upload-artifact@v3
          with:
            name: dev_build
            path: dev_build.txt
          
