# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Scheme:
        type: choice
        # Default value if no value is selected
        default: 'AssetStorage'
        # Input has to be provided for the workflow to run
        required: true
        options:
        - AssetStorage
        - AssetStorageBeta
        - AssetStorageRelease
      Note:
        description: 'Add release notes for this build'
        default: 'This build is ready for testing'
        required: true
env:
  dev_build: ${{ vars.DEV_BUILD_NUMBER }}
                

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  build:
    name: Build [${{ github.event.inputs.Scheme }}]
    env: # overrides: https://github.com/mbitsnbites/buildcache/blob/master/doc/configuration.md
      BUILDCACHE_DIR: ../.buildcache # optional: Put the cache somewhere else
      BUILDCACHE_DEBUG: 2 # optional: If you need more logging?
      BUILDCACHE_MAX_CACHE_SIZE: 1000000000 # optional: Need a bigger cache?
      BUILDCACHE_LOG_FILE: ../buildcache.log
    runs-on: macos-latest

    steps:  
      - name: Restore buildcache
        uses: mikehardy/buildcache-action@v1
        continue-on-error: true
        with:
          cache_key: ${{ matrix.os }} # optional: separate caches maybe?
          upload_buildcache_log: 'true' # optional: 100% cache misses? Find out why
          zero_buildcache_stats: 'false' # optional: lifetime vs per-run stats?

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          
      - name: Build
        run: |
          "xcodebuild \
          CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ \
          -derivedDataPath ios/build -UseModernBuildSystem=YES \
          -workspace AssetStorage.xcworkspace \
          -scheme AssetStorage \
          -sdk iphonesimulator \
          -configuration Debug \
          -destination \"generic/platform=iOS Simulator\" \
          build \
          CODE_SIGNING_ALLOWED=NO"

      - name: Fail check
        if: ${{ cancelled() }}
        run: |
          echo: "Cancelled by user"
          
