# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Scheme:
        type: choice
        # Default value if no value is selected
        default: 'AssetStorage'
        # Input has to be provided for the workflow to run
        required: true
        options:
        - AssetStorage
        - AssetStorageBeta
        - AssetStorageRelease
      Note:
        description: 'Add release notes for this build'
        default: 'This build is ready for testing'
        required: true
env:
  dev_build: ${{ vars.DEV_BUILD_NUMBER }}
                

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  build:
    name: Build [${{ github.event.inputs.Scheme }}]
    env: # overrides: https://github.com/mbitsnbites/buildcache/blob/master/doc/configuration.md
      BUILDCACHE_DIR: ../.buildcache # optional: Put the cache somewhere else
      BUILDCACHE_DEBUG: 2 # optional: If you need more logging?
      BUILDCACHE_MAX_CACHE_SIZE: 1000000000 # optional: Need a bigger cache?
      BUILDCACHE_LOG_FILE: ../buildcache.log
    runs-on: macos-latest

    steps:  
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C040Y3ACZM1'
          payload: |
            {
              "text": "`${{ github.actor }}` Started distributing build",
              "attachments": [
                {
                  "pretext": "",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress.."
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send Failure GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'C040Y3ACZM1'
          payload: |
            {
              "text": "Failed to build",
              "attachments": [
                {
                  "pretext": "",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": false,
                      "value": "Failed"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          
