# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      Scheme:
        type: choice
        # Default value if no value is selected
        default: 'SPDev'
        # Input has to be provided for the workflow to run
        required: true
        options:
        - SPDev
        - SPTest
        - SPBeta
      Note:
        description: 'Add release notes for this build'
        default: 'This build is ready for testing'
        required: true
                

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Scheme selected ${{ github.event.inputs.Scheme }} Message ${{ github.event.inputs.Note }}"
